version: '3.7'
services:
    sabnzbd:
        build: sabnzbd
        image: cronos/sabnzbd
        hostname: sabnzbd
        restart: unless-stopped
        volumes:
            - $PWD/data/usenet:/data/usenet
            - $PWD/config/sabnzbd:/home/sabnzbd/.sabnzbd
        ports:
            - "127.0.0.1:8080:8080/tcp"
    sonarr:
        build: sonarr
        image: cronos/sonarr
        hostname: sonarr
        restart: unless-stopped
        volumes:
            - $PWD/data:/data
            - $PWD/config/sonarr:/home/sonarr/.config/Sonarr
        ports:
            - "127.0.0.1:8989:8989/tcp"
        depends_on:
            - "sabnzbd"
    radarr:
        build: radarr
        image: cronos/radarr
        hostname: radarr
        restart: unless-stopped
        volumes:
            - $PWD/data:/data
            - $PWD/config/radarr:/home/radarr/.config/Radarr
        ports:
            - "127.0.0.1:7878:7878/tcp"
        depends_on:
            - "sabnzbd"
    nzbhydra2:
        build: nzbhydra2
        image: cronos/nzbhydra2
        hostname: nzbhydra2
        restart: unless-stopped
        volumes:
            - $PWD/config/nzbhydra2:/config
        ports:
            - "127.0.0.1:5076:5076/tcp"
        depends_on:
            - "sabnzbd"
    plex:
        image: linuxserver/plex
        hostname: plex
        container_name: plex
        network_mode: host
        environment:
            - PUID=1000
            - PGID=1000
            - VERSION=docker
            - UMASK=022
        volumes:
            - $PWD/config/plex:/config
            - $PWD/config/plex-transcode:/transcode
            - $PWD/data:/data:ro
        restart: unless-stopped
